apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  annotations:
    kapp.k14s.io/change-group: "setup"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-cert
  annotations:
    kapp.k14s.io/change-group: "setup"
spec:
  secretName: ais-tls-certs
  dnsNames:
    - aistore-sample-proxy
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer