apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base

patches:
- patch: |
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: StatefulSet
    name: ais-proxy
- patch: |
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: StatefulSet
    name: ais-target 