apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ais-proxy
spec:
  template:
    spec:
      containers:
      - name: aisnode
        livenessProbe:
          httpGet:
            scheme: HTTPS
        readinessProbe:
          httpGet:
            scheme: HTTPS
        volumeMounts:
        - name: ais-tls-certs
          mountPath: /var/certs
      volumes:
      - name: ais-tls-certs
        secret:
          secretName: ais-tls-certs
          optional: true