apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ais

resources:
- namespace.yaml
- rbac.yaml
- proxy/svc.yaml
- proxy/statefulset.yaml
- target/svc.yaml
- target/statefulset.yaml

images:
- name: aistorage/aisnode
  newTag: latest
- name: aistorage/ais-init  
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    app: ais

configMapGenerator:
- name: ais-cluster-config-override
  files:
    - ais_cluster_override.json
  options:
    annotations:
      kapp.k14s.io/change-group: "setup"
- name: ais-proxy-local-config-template
  files:
    - proxy/ais_local_template.json
  options:
    annotations:
      kapp.k14s.io/change-group: "setup"
- name: ais-target-local-config-template
  files:
    - target/ais_local_template.json
  options:
    annotations:
      kapp.k14s.io/change-group: "setup"

replacements:
- source:
    kind: StatefulSet
    name: ais-target
    fieldPath: spec.replicas
  targets:
  - select:
      kind: StatefulSet
      name: ais-proxy
    fieldPaths:
    - spec.template.spec.containers.[name=aisnode].args.[=-ntargets=1]
    options:
      delimiter: '='
      index: 1 