apiVersion: v1
kind: ServiceAccount
metadata:
  name: ais
  annotations:
    kapp.k14s.io/change-group: "setup"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ais-rbac
  annotations:
    kapp.k14s.io/change-group: "setup"
subjects:
  - kind: ServiceAccount
    name: ais
    namespace: ais
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io