apiVersion: v1
kind: Pod
metadata:
  name: <NAME>
spec:
  containers:
    - name: server
      image: aistorage/runtime_python:<TAG>
      imagePullPolicy: Always
      ports:
        - name: default
          containerPort: 80
      command: <COMMAND>
      # Reference: https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/#customizing-the-termination-message
      # TODO: The ETL pod error log captured using this method may be truncated. Consider storing the full log in a persistent location for users to inspect.
      terminationMessagePolicy: FallbackToLogsOnError
      env:
        - name: MOD_NAME
          value: code
        - name: FUNC_TRANSFORM
          value: <FUNC_TRANSFORM>
        - name: COMM_TYPE
          value: <COMM_TYPE>
        - name: CHUNK_SIZE
          value: <CHUNK_SIZE>
        - name: ARG_TYPE
          value: <ARG_TYPE>
        - name: FLAGS
          value: <FLAGS>
        - name: PYTHONPATH
          value: /runtime
      readinessProbe:
        httpGet:
          path: /health
          port: default
      volumeMounts:
        - name: code
          mountPath: "/code"
        - name: runtime
          mountPath: "/runtime"
  initContainers:
    - name: server-deps
      image: aistorage/runtime_python:<TAG>
      imagePullPolicy: Always
      command:
        - 'sh'
        - '-c'
        - |
          echo "${AISTORE_CODE}" > /dst/code.py
          echo "${AISTORE_DEPS}" > /dst/requirements.txt
          pip install --target="/runtime" -r /dst/requirements.txt
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - name: code
          mountPath: "/dst"
        - name: runtime
          mountPath: "/runtime"
  volumes:
    - name: code
      emptyDir: {}
    - name: runtime
      emptyDir: {}
