name: Deploy Website

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy_website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Prepare docs with front-matter
        run: |
          ./scripts/website-preprocess.sh

      - name: Build and deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          # ── build inside docs ───────────────────
          cd docs
          bundle install --quiet
          bundle exec jekyll build
          # ── deploy from repo root ───────────────
          cd "$GITHUB_WORKSPACE"
          npm install -g netlify-cli
          netlify deploy --dir=docs/_site --prod
