name: Go Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.24.x']
        # os: [ubuntu-latest, macos-latest]
        # TODO: provide support for MacOS (!1169)
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install s3cmd via pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user s3cmd
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure system
        run: |
          sudo sysctl -w vm.swappiness=10

      - name: Run and test AIStore
        run: |
          export GOPATH="$(go env GOPATH)"
          scripts/clean_deploy.sh --target-cnt 3 --proxy-cnt 1 --mountpath-cnt 2
          NUM_PROXY=1 NUM_TARGET=3 BUCKET="ais://test" make test-short
