name: Python SDK Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.22.x']
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup additional system libraries
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y xattr attr

      - name: Run AIStore
        run: |
          export GOPATH="$(go env GOPATH)"
          scripts/clean_deploy.sh --target-cnt 1 --proxy-cnt 1 --mountpath-cnt 1

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Python tests
        run: |
          cd python
          make python_sdk_tests
          make python_botocore_tests
